# Generated by Django 4.2.1 on 2023-05-31 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountApp', '0002_review_reviewlikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientinfo',
            name='locations',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
