# Generated by Django 4.2.1 on 2023-06-01 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountApp', '0003_patientinfo_locations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orginfo',
            old_name='address',
            new_name='parmanent_address',
        ),
        migrations.RenameField(
            model_name='patientinfo',
            old_name='contuct_no',
            new_name='phone_no',
        ),
        migrations.AddField(
            model_name='orginfo',
            name='pres_address',
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='fb',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='instra',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='parmanent_address',
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='pres_address',
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='tw',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
