# Generated by Django 4.2.1 on 2023-06-01 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountApp', '0004_rename_address_orginfo_parmanent_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientinfo',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
