# Generated by Django 4.2.1 on 2023-06-01 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AccountApp', '0005_patientinfo_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stutas', models.CharField(choices=[(None, 'Select Blood Group'), ('ACCEPT', 'ACCEPT'), ('REJECT', 'REJECT')], default=None, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Recipient', to=settings.AUTH_USER_MODEL)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
