# Generated by Django 4.2.1 on 2023-06-02 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountApp', '0007_rename_recipient_donerrequest_recipient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donerrequest',
            name='stutas',
            field=models.CharField(choices=[(None, 'Select'), ('ACCEPT', 'ACCEPT'), ('REJECT', 'REJECT')], default=None, max_length=10),
        ),
    ]
